// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD89YAdoYqitCwoUOMOxdniCkwkc5IpTZU',
    appId: '1:787079131112:web:598f9bf0f38e4421f57e5d',
    messagingSenderId: '787079131112',
    projectId: 'todolist-37f36',
    authDomain: 'todolist-37f36.firebaseapp.com',
    storageBucket: 'todolist-37f36.appspot.com',
    measurementId: 'G-GDPG89DLT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU3CIyvk6UGGRcgFnAt8y49qPH5W3Ht80',
    appId: '1:787079131112:android:4bbdbe69d89c791bf57e5d',
    messagingSenderId: '787079131112',
    projectId: 'todolist-37f36',
    storageBucket: 'todolist-37f36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvNtntkZI73Cg54n5Ig_F8fKTQUjEJXBw',
    appId: '1:787079131112:ios:c1212d797ae84a00f57e5d',
    messagingSenderId: '787079131112',
    projectId: 'todolist-37f36',
    storageBucket: 'todolist-37f36.appspot.com',
    iosClientId: '787079131112-v54pohd7cp3996gslhcvfskt31lqgq3b.apps.googleusercontent.com',
    iosBundleId: 'com.todolist.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvNtntkZI73Cg54n5Ig_F8fKTQUjEJXBw',
    appId: '1:787079131112:ios:c1212d797ae84a00f57e5d',
    messagingSenderId: '787079131112',
    projectId: 'todolist-37f36',
    storageBucket: 'todolist-37f36.appspot.com',
    iosClientId: '787079131112-v54pohd7cp3996gslhcvfskt31lqgq3b.apps.googleusercontent.com',
    iosBundleId: 'com.todolist.todolist',
  );
}
